### ISSUE TITLE
Ability to add external roles / sources

### ISSUE THREAD

**Issue by magroader** [bra1n/grimoire#7]
My group makes quite a few Homebrew roles. It would be nice to be able to add these homebrew roles to the tool.

Some possible options for this (per-server):
* Adding roles directly, like via `!addrole "Rolename" "Description" "Ability"` / `!updaterole` / `!removerole` set of commands
* Adding external json files for lookups, e.g. `!addsource "Set Name" http://path/to/script.json` / `!removesource`

**Comment by bra1n** [comment]
Hm, I don't think this is going to work. The bot doesn't have any kind of database or local persistence to remember stuff, so you would have to reload your homebrew scripts every time the bot has to restart. On top of that, keeping things like this in memory is also not going to work long-term, because the bot isn't only being used on your Discord. If there ever is going to be an online database of homebrew scripts, it could hook into that and pull any homebrew roles with matching names on demand, but before that happens I think it's rather unlikely to get added to the bot.
